server:
  port: 4399
spring:
  application:
    name: yigou-zuul-gateway-dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-4399.com
    prefer-ip-address: true
zuul:
  routes:
    plat.serviceId: yigou-plat-dev #这是调用满足条件的服务名，注意要小写
    plat.path: /plat/** #这是所有路径前的通配
    product.serviceId: yigou-product #这是调用满足条件的服务名，注意要小写
    product.path: /product/** #这是所有路径前的通配
  ignored-services: "*" #用*来通配符，忽略从9527端口通过服务名来调用
  prefix: "/services" #这是所有路径的前缀
